In [1]:
import torch

torch.manual_seed(0)

d:\IR\Experiment\.venv\Lib\site-packages\torch\_subclasses\functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [9]:
a =     torch.ones(4, 3, 2)

print(a)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])


In [17]:
b_rand = torch.rand(   3, 2)

print(b_rand)

tensor([[0.5846, 0.0332],
        [0.1387, 0.2422],
        [0.8155, 0.7932]])


In [10]:
m = torch.nn.ReLU()
inp = torch.randn(2, 3)
print(inp)
output = m(inp)

print(output)

tensor([[ 0.1919,  1.2638, -1.2904],
        [-0.7911, -0.0209, -0.7185]])
tensor([[0.1919, 1.2638, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [11]:
X = torch.randn(2, 3)
print(X)
print(torch.maximum(torch.zeros_like(X), X))

tensor([[ 0.5186, -1.3125,  0.1920],
        [ 0.5428, -2.2188,  0.2590]])
tensor([[0.5186, 0.0000, 0.1920],
        [0.5428, 0.0000, 0.2590]])
